# Generated by Django 6.0.1 on 2026-01-31

from django.db import migrations


def create_zte_vendor_profile(apps, schema_editor):
    VendorProfile = apps.get_model("dashboard", "VendorProfile")

    oid_templates = {
        "indexing": {
            "format": "pon_onu",
            "pon_encoding": "0x11rrsspp",
            "slot_from": "shelf",
            "pon_from": "port",
        },
        "discovery": {
            "onu_name_oid": "1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.2",
            "onu_serial_oid": "1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.18",
            "onu_status_oid": "1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.4",
        },
        "status": {
            "onu_status_oid": "1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.4",
            "status_map": {
                "1": {"status": "unknown", "reason": "unknown"},
                "2": {"status": "unknown", "reason": "unknown"},
                "3": {"status": "unknown", "reason": "unknown"},
                "4": {"status": "online"},
                "5": {"status": "unknown", "reason": "unknown"},
                "6": {"status": "unknown", "reason": "unknown"},
                "7": {"status": "unknown", "reason": "unknown"},
            },
        },
        "power": {
            "olt_rx_oid": "1.3.6.1.4.1.3902.1082.500.1.2.4.2.1.2",
            "onu_rx_oid": "1.3.6.1.4.1.3902.1082.500.20.2.2.2.1.10",
            "onu_rx_suffix": "1",
        },
    }

    VendorProfile.objects.update_or_create(
        vendor="zte",
        model_name="C300",
        defaults={
            "description": "ZTE C300 OID templates for ONU discovery and status",
            "oid_templates": oid_templates,
            "supports_onu_discovery": True,
            "supports_onu_status": True,
            "supports_power_monitoring": True,
            "supports_disconnect_reason": True,
            "default_thresholds": {},
            "is_active": True,
        },
    )


def remove_zte_vendor_profile(apps, schema_editor):
    VendorProfile = apps.get_model("dashboard", "VendorProfile")
    VendorProfile.objects.filter(vendor="zte", model_name="C300").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_zte_vendor_profile, remove_zte_vendor_profile),
    ]
