# Generated by Django 6.0.1 on 2026-01-31

import django.db.models.deletion
from django.db import migrations, models


def _decode_zte_pon_id(pon_id: int):
    if pon_id < 0:
        return None
    if ((pon_id >> 24) & 0xFF) != 0x11:
        return None
    return {
        "rack_id": (pon_id >> 16) & 0xFF,
        "shelf_id": (pon_id >> 8) & 0xFF,
        "port_id": pon_id & 0xFF,
    }


def _slot_key(slot_id: int, rack_id=None, shelf_id=None):
    if rack_id is not None and shelf_id is not None:
        return f"{rack_id}/{shelf_id}"
    return str(slot_id)


def _pon_key(slot_id: int, pon_id: int, rack_id=None, shelf_id=None, port_id=None):
    if rack_id is not None and shelf_id is not None and port_id is not None:
        return f"{rack_id}/{shelf_id}/{port_id}"
    return f"{slot_id}/{pon_id}"


def backfill_slots_and_pons(apps, schema_editor):
    OLTSlot = apps.get_model("dashboard", "OLTSlot")
    OLTPON = apps.get_model("dashboard", "OLTPON")
    ONU = apps.get_model("dashboard", "ONU")

    slot_cache = {}
    pon_cache = {}

    for onu in ONU.objects.select_related("olt"):
        pon_numeric = None
        rack_id = shelf_id = port_id = None

        if onu.snmp_index:
            parts = str(onu.snmp_index).split(".")
            if parts and parts[0].isdigit():
                try:
                    pon_numeric = int(parts[0])
                except ValueError:
                    pon_numeric = None
        if pon_numeric is not None:
            decoded = _decode_zte_pon_id(pon_numeric)
            if decoded:
                rack_id = decoded.get("rack_id")
                shelf_id = decoded.get("shelf_id")
                port_id = decoded.get("port_id")

        slot_key = _slot_key(onu.slot_id, rack_id=rack_id, shelf_id=shelf_id)
        slot_cache_key = (onu.olt_id, slot_key)
        slot = slot_cache.get(slot_cache_key)
        if slot is None:
            slot, _ = OLTSlot.objects.get_or_create(
                olt_id=onu.olt_id,
                slot_key=slot_key,
                defaults={
                    "slot_id": onu.slot_id,
                    "rack_id": rack_id,
                    "shelf_id": shelf_id,
                    "is_active": True,
                },
            )
            slot_cache[slot_cache_key] = slot

        pon_key = _pon_key(onu.slot_id, onu.pon_id, rack_id=rack_id, shelf_id=shelf_id, port_id=port_id)
        pon_cache_key = (slot.id, onu.pon_id)
        if pon_cache_key not in pon_cache:
            pon, _ = OLTPON.objects.get_or_create(
                slot_id=slot.id,
                pon_id=onu.pon_id,
                defaults={
                    "olt_id": onu.olt_id,
                    "pon_key": pon_key,
                    "pon_index": pon_numeric,
                    "rack_id": rack_id,
                    "shelf_id": shelf_id,
                    "port_id": port_id,
                    "is_active": True,
                },
            )
            pon_cache[pon_cache_key] = pon


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_zte_vendor_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="OLTSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot_id", models.IntegerField(verbose_name="Slot ID")),
                ("rack_id", models.IntegerField(blank=True, null=True, verbose_name="Rack ID")),
                ("shelf_id", models.IntegerField(blank=True, null=True, verbose_name="Shelf ID")),
                ("slot_key", models.CharField(max_length=100, verbose_name="Chave do Slot")),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="Nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("last_discovered_at", models.DateTimeField(auto_now=True, verbose_name="Última Descoberta")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("olt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="dashboard.olt", verbose_name="OLT")),
            ],
            options={
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
                "unique_together": {("olt", "slot_key")},
            },
        ),
        migrations.CreateModel(
            name="OLTPON",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pon_id", models.IntegerField(verbose_name="PON ID")),
                ("pon_index", models.BigIntegerField(blank=True, null=True, verbose_name="Índice PON SNMP")),
                ("rack_id", models.IntegerField(blank=True, null=True, verbose_name="Rack ID")),
                ("shelf_id", models.IntegerField(blank=True, null=True, verbose_name="Shelf ID")),
                ("port_id", models.IntegerField(blank=True, null=True, verbose_name="Port ID")),
                ("pon_key", models.CharField(max_length=120, verbose_name="Chave do PON")),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="Nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("last_discovered_at", models.DateTimeField(auto_now=True, verbose_name="Última Descoberta")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("olt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pons", to="dashboard.olt", verbose_name="OLT")),
                ("slot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pons", to="dashboard.oltslot", verbose_name="Slot")),
            ],
            options={
                "verbose_name": "PON",
                "verbose_name_plural": "PONs",
                "unique_together": {("slot", "pon_id")},
            },
        ),
        migrations.AddIndex(
            model_name="oltslot",
            index=models.Index(fields=["olt", "slot_id"], name="dashboard_o_olt_id_1fd7ed_idx"),
        ),
        migrations.AddIndex(
            model_name="oltslot",
            index=models.Index(fields=["olt", "slot_key"], name="dashboard_o_olt_id_4e23d0_idx"),
        ),
        migrations.AddIndex(
            model_name="oltpon",
            index=models.Index(fields=["olt", "pon_id"], name="dashboard_o_olt_id_76b9d5_idx"),
        ),
        migrations.AddIndex(
            model_name="oltpon",
            index=models.Index(fields=["slot", "pon_id"], name="dashboard_o_slot_i_2cb314_idx"),
        ),
        migrations.RunPython(backfill_slots_and_pons, migrations.RunPython.noop),
    ]
