# Generated by Django 6.0.1 on 2026-01-31

from django.db import migrations


def add_zte_pon_interfaces(apps, schema_editor):
    VendorProfile = apps.get_model("dashboard", "VendorProfile")
    profile = VendorProfile.objects.filter(vendor="zte", model_name="C300").first()
    if not profile:
        return

    templates = profile.oid_templates or {}
    templates["pon_interfaces"] = {
        "name_oid": "1.3.6.1.2.1.31.1.1.1.1",
        "status_oid": "1.3.6.1.2.1.2.2.1.8",
        "name_regex": r"^gpon_(\d+)/(\d+)/(\d+)$",
        "status_up": "1",
    }
    profile.oid_templates = templates
    profile.save(update_fields=["oid_templates"])


def remove_zte_pon_interfaces(apps, schema_editor):
    VendorProfile = apps.get_model("dashboard", "VendorProfile")
    profile = VendorProfile.objects.filter(vendor="zte", model_name="C300").first()
    if not profile:
        return

    templates = profile.oid_templates or {}
    templates.pop("pon_interfaces", None)
    profile.oid_templates = templates
    profile.save(update_fields=["oid_templates"])


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_olt_topology_map"),
    ]

    operations = [
        migrations.RunPython(add_zte_pon_interfaces, remove_zte_pon_interfaces),
    ]
