# Generated by Django 6.0.1 on 2026-01-31

import django.db.models.deletion
from django.db import migrations, models


def _decode_zte_pon_id(pon_id: int):
    if pon_id < 0:
        return None
    if ((pon_id >> 24) & 0xFF) != 0x11:
        return None
    return {
        "rack_id": (pon_id >> 16) & 0xFF,
        "shelf_id": (pon_id >> 8) & 0xFF,
        "port_id": pon_id & 0xFF,
    }


def _slot_key(slot_id: int, rack_id=None, shelf_id=None):
    if rack_id is not None and shelf_id is not None:
        return f"{rack_id}/{shelf_id}"
    return str(slot_id)


def _pon_key(slot_id: int, pon_id: int, rack_id=None, shelf_id=None, port_id=None):
    if rack_id is not None and shelf_id is not None and port_id is not None:
        return f"{rack_id}/{shelf_id}/{port_id}"
    return f"{slot_id}/{pon_id}"


def backfill_onu_links(apps, schema_editor):
    OLTSlot = apps.get_model("dashboard", "OLTSlot")
    OLTPON = apps.get_model("dashboard", "OLTPON")
    ONU = apps.get_model("dashboard", "ONU")

    slot_cache = {}
    pon_cache = {}

    for onu in ONU.objects.select_related("olt"):
        rack_id = shelf_id = port_id = None
        pon_numeric = None
        if onu.snmp_index:
            parts = str(onu.snmp_index).split(".")
            if parts and parts[0].isdigit():
                try:
                    pon_numeric = int(parts[0])
                except ValueError:
                    pon_numeric = None
        if pon_numeric is not None:
            decoded = _decode_zte_pon_id(pon_numeric)
            if decoded:
                rack_id = decoded.get("rack_id")
                shelf_id = decoded.get("shelf_id")
                port_id = decoded.get("port_id")

        slot_key = _slot_key(onu.slot_id, rack_id=rack_id, shelf_id=shelf_id)
        slot_cache_key = (onu.olt_id, slot_key)
        slot = slot_cache.get(slot_cache_key)
        if slot is None:
            slot, _ = OLTSlot.objects.get_or_create(
                olt_id=onu.olt_id,
                slot_key=slot_key,
                defaults={
                    "slot_id": onu.slot_id,
                    "rack_id": rack_id,
                    "shelf_id": shelf_id,
                    "is_active": True,
                },
            )
            slot_cache[slot_cache_key] = slot

        pon_cache_key = (slot.id, onu.pon_id)
        pon = pon_cache.get(pon_cache_key)
        if pon is None:
            pon_key = _pon_key(onu.slot_id, onu.pon_id, rack_id=rack_id, shelf_id=shelf_id, port_id=port_id)
            pon, _ = OLTPON.objects.get_or_create(
                slot_id=slot.id,
                pon_id=onu.pon_id,
                defaults={
                    "olt_id": onu.olt_id,
                    "pon_key": pon_key,
                    "pon_index": pon_numeric,
                    "rack_id": rack_id,
                    "shelf_id": shelf_id,
                    "port_id": port_id,
                    "is_active": True,
                },
            )
            pon_cache[pon_cache_key] = pon

        ONU.objects.filter(pk=onu.pk).update(slot_ref_id=slot.id, pon_ref_id=pon.id)


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_zte_pon_interfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="onu",
            name="slot_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onus",
                to="dashboard.oltslot",
                verbose_name="Slot",
            ),
        ),
        migrations.AddField(
            model_name="onu",
            name="pon_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onus",
                to="dashboard.oltpon",
                verbose_name="PON",
            ),
        ),
        migrations.RunPython(backfill_onu_links, migrations.RunPython.noop),
    ]
