# Generated by Django 4.2.27 on 2026-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_vendor_profile_intervals'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='onu',
            name='dashboard_o_olt_id_580ab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='onu',
            name='dashboard_o_snmp_in_903c43_idx',
        ),
        migrations.AddField(
            model_name='olt',
            name='last_snmp_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação SNMP'),
        ),
        migrations.AddField(
            model_name='olt',
            name='last_snmp_error',
            field=models.TextField(blank=True, default='', verbose_name='Último Erro SNMP'),
        ),
        migrations.AddField(
            model_name='olt',
            name='snmp_failure_count',
            field=models.IntegerField(default=0, verbose_name='Falhas SNMP Consecutivas'),
        ),
        migrations.AddField(
            model_name='olt',
            name='snmp_reachable',
            field=models.BooleanField(blank=True, null=True, verbose_name='SNMP Acessível'),
        ),
        migrations.AddField(
            model_name='onu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='onu',
            name='snmp_index',
            field=models.CharField(max_length=200, verbose_name='Índice SNMP'),
        ),
        migrations.AlterField(
            model_name='onulog',
            name='disconnect_reason',
            field=models.CharField(choices=[('link_loss', 'Rompimento'), ('dying_gasp', 'Sem Energia'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Motivo da Desconexão'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor',
            field=models.CharField(max_length=50, verbose_name='Fabricante'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'is_active', 'slot_id', 'pon_id'], name='dashboard_o_olt_id_4b24ff_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'snmp_index'], name='dashboard_o_olt_id_2581e1_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'is_active', 'status'], name='dashboard_o_olt_id_d0ec99_idx'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('olt', 'snmp_index'), name='dashboard_unique_olt_snmp_index'),
        ),
    ]
