# Generated by Django 4.2.27 on 2026-02-14 15:20

from django.db import migrations


DISABLE_LOST_AFTER_MINUTES = 60
DELETE_LOST_AFTER_MINUTES = 10080  # 7 days


def apply_zte_lost_resource_policy(apps, schema_editor):
    VendorProfile = apps.get_model("dashboard", "VendorProfile")
    profile = VendorProfile.objects.filter(vendor__iexact="zte", model_name__iexact="C300").first()
    if not profile:
        return

    templates = dict(profile.oid_templates or {})
    changed = False

    status_cfg = dict(templates.get("status") or {})
    status_map = dict(status_cfg.get("status_map") or {})
    canonical = {
        "2": {"status": "offline", "reason": "link_loss"},
        "5": {"status": "offline", "reason": "dying_gasp"},
    }
    for code, target in canonical.items():
        current = status_map.get(code)
        if not isinstance(current, dict) or current.get("status") != target["status"] or current.get("reason") != target["reason"]:
            status_map[code] = target
            changed = True

    if status_map:
        status_cfg["status_map"] = status_map
        templates["status"] = status_cfg

    discovery_cfg = dict(templates.get("discovery") or {})
    if "deactivate_missing" not in discovery_cfg:
        discovery_cfg["deactivate_missing"] = True
        changed = True
    if "disable_lost_after_minutes" not in discovery_cfg and "keep_lost_minutes" not in discovery_cfg:
        discovery_cfg["disable_lost_after_minutes"] = DISABLE_LOST_AFTER_MINUTES
        changed = True
    if "delete_lost_after_minutes" not in discovery_cfg:
        discovery_cfg["delete_lost_after_minutes"] = DELETE_LOST_AFTER_MINUTES
        changed = True

    templates["discovery"] = discovery_cfg

    if changed:
        profile.oid_templates = templates
        profile.save(update_fields=["oid_templates"])


def noop_reverse(apps, schema_editor):
    # Keep user-edited vendor profile settings intact on migration rollback.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_onu_dashboard_o_olt_id_580ab2_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(apply_zte_lost_resource_policy, noop_reverse),
    ]
