# Generated by Django 4.2.27 on 2026-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_zte_lost_resource_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='power_interval_seconds',
            field=models.IntegerField(default=300, help_text='Com que frequência atualizar leituras de potência das ONUs', verbose_name='Intervalo de Potência (segundos)'),
        ),
    ]
