# Generated by Django 4.2.27 on 2026-02-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('protocol', models.CharField(choices=[('snmp', 'SNMP')], default='snmp', max_length=20, verbose_name='Protocolo')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('snmp_port', models.IntegerField(default=161, verbose_name='Porta SNMP')),
                ('snmp_community', models.CharField(max_length=100, verbose_name='Comunidade SNMP')),
                ('snmp_version', models.CharField(choices=[('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=10, verbose_name='Versão SNMP')),
                ('discovery_enabled', models.BooleanField(default=True, verbose_name='Descoberta Ativada')),
                ('discovery_interval_minutes', models.IntegerField(default=240, help_text='Com que frequência descobrir a estrutura da OLT (slots, PONs, ONUs)', verbose_name='Intervalo de Descoberta (minutos)')),
                ('last_discovery_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Descoberta')),
                ('next_discovery_at', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Descoberta')),
                ('discovery_healthy', models.BooleanField(default=True, verbose_name='Descoberta Saudável')),
                ('polling_enabled', models.BooleanField(default=True, verbose_name='Polling Ativado')),
                ('polling_interval_seconds', models.IntegerField(default=300, help_text='Com que frequência verificar o status online/offline das ONUs', verbose_name='Intervalo de Polling (segundos)')),
                ('power_interval_seconds', models.IntegerField(default=300, help_text='Com que frequência atualizar leituras de potência das ONUs', verbose_name='Intervalo de Potência (segundos)')),
                ('last_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Polling')),
                ('next_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Polling')),
                ('snmp_reachable', models.BooleanField(blank=True, null=True, verbose_name='SNMP Acessível')),
                ('last_snmp_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação SNMP')),
                ('last_snmp_error', models.TextField(blank=True, default='', verbose_name='Último Erro SNMP')),
                ('snmp_failure_count', models.IntegerField(default=0, verbose_name='Falhas SNMP Consecutivas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTs',
            },
        ),
        migrations.CreateModel(
            name='OLTPON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pon_id', models.IntegerField(verbose_name='PON ID')),
                ('pon_index', models.BigIntegerField(blank=True, null=True, verbose_name='Índice PON SNMP')),
                ('rack_id', models.IntegerField(blank=True, null=True, verbose_name='Rack ID')),
                ('shelf_id', models.IntegerField(blank=True, null=True, verbose_name='Shelf ID')),
                ('port_id', models.IntegerField(blank=True, null=True, verbose_name='Port ID')),
                ('pon_key', models.CharField(max_length=120, verbose_name='Chave do PON')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_discovered_at', models.DateTimeField(auto_now=True, verbose_name='Última Descoberta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pons', to='topology.olt', verbose_name='OLT')),
            ],
            options={
                'verbose_name': 'PON',
                'verbose_name_plural': 'PONs',
            },
        ),
        migrations.CreateModel(
            name='OLTSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(verbose_name='Slot ID')),
                ('rack_id', models.IntegerField(blank=True, null=True, verbose_name='Rack ID')),
                ('shelf_id', models.IntegerField(blank=True, null=True, verbose_name='Shelf ID')),
                ('slot_key', models.CharField(max_length=100, verbose_name='Chave do Slot')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_discovered_at', models.DateTimeField(auto_now=True, verbose_name='Última Descoberta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='topology.olt', verbose_name='OLT')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(verbose_name='Slot ID')),
                ('pon_id', models.IntegerField(verbose_name='PON ID')),
                ('onu_id', models.IntegerField(verbose_name='ONU ID')),
                ('snmp_index', models.CharField(max_length=200, verbose_name='Índice SNMP')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('last_discovered_at', models.DateTimeField(auto_now=True, verbose_name='Última Descoberta')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='topology.olt', verbose_name='OLT')),
                ('pon_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='topology.oltpon', verbose_name='PON')),
                ('slot_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='topology.oltslot', verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'ONU',
                'verbose_name_plural': 'ONUs',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('oid_templates', models.JSONField(default=dict, verbose_name='Templates de OID')),
                ('supports_onu_discovery', models.BooleanField(default=True, verbose_name='Suporta Descoberta de ONU')),
                ('supports_onu_status', models.BooleanField(default=True, verbose_name='Suporta Status de ONU')),
                ('supports_power_monitoring', models.BooleanField(default=True, verbose_name='Suporta Monitoramento de Potência')),
                ('supports_disconnect_reason', models.BooleanField(default=True, verbose_name='Suporta Motivo de Desconexão')),
                ('default_thresholds', models.JSONField(default=dict, verbose_name='Limites Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Perfil de Fabricante',
                'verbose_name_plural': 'Perfis de Fabricante',
                'indexes': [models.Index(fields=['vendor'], name='topology_ve_vendor_2c3d53_idx')],
                'unique_together': {('vendor', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Leitor')], default='viewer', max_length=20, verbose_name='Função')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP de Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.AddField(
            model_name='oltpon',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pons', to='topology.oltslot', verbose_name='Slot'),
        ),
        migrations.AddField(
            model_name='olt',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olts', to='topology.vendorprofile', verbose_name='Perfil de Fabricante'),
        ),
        migrations.CreateModel(
            name='ONULog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_since', models.DateTimeField(verbose_name='Offline Desde')),
                ('offline_until', models.DateTimeField(blank=True, null=True, verbose_name='Offline Até')),
                ('disconnect_reason', models.CharField(choices=[('link_loss', 'Rompimento'), ('dying_gasp', 'Sem Energia'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Motivo da Desconexão')),
                ('onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='topology.onu', verbose_name='ONU')),
            ],
            options={
                'verbose_name': 'Log de ONU',
                'verbose_name_plural': 'Logs de ONU',
                'indexes': [models.Index(fields=['onu', '-offline_since'], name='topology_on_onu_id_857c8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'is_active', 'slot_id', 'pon_id'], name='topology_on_olt_id_e558de_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'snmp_index'], name='topology_on_olt_id_8f3532_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'is_active', 'status'], name='topology_on_olt_id_e3972f_idx'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('olt', 'snmp_index'), name='topology_unique_olt_snmp_index'),
        ),
        migrations.AlterUniqueTogether(
            name='onu',
            unique_together={('olt', 'slot_id', 'pon_id', 'onu_id')},
        ),
        migrations.AddIndex(
            model_name='oltslot',
            index=models.Index(fields=['olt', 'slot_id'], name='topology_o_olt_id_1fd7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='oltslot',
            index=models.Index(fields=['olt', 'slot_key'], name='topology_o_olt_id_4e23d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oltslot',
            unique_together={('olt', 'slot_key')},
        ),
        migrations.AddIndex(
            model_name='oltpon',
            index=models.Index(fields=['olt', 'pon_id'], name='topology_o_olt_id_76b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='oltpon',
            index=models.Index(fields=['slot', 'pon_id'], name='topology_o_slot_i_2cb314_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oltpon',
            unique_together={('slot', 'pon_id')},
        ),
        migrations.AddIndex(
            model_name='olt',
            index=models.Index(fields=['vendor_profile'], name='topology_ol_vendor__a0a560_idx'),
        ),
    ]
