# Generated by Django 4.2.28 on 2026-02-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_seed_zte_vendor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltpon',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
