# Generated by Django 4.2.27 on 2026-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_oltpon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='last_power_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Coleta de Potência'),
        ),
        migrations.AddField(
            model_name='olt',
            name='next_power_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Coleta de Potência'),
        ),
    ]
