# Generated by Django 4.2.27 on 2026-02-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0004_olt_last_power_at_olt_next_power_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onulog',
            name='disconnect_window_end',
            field=models.DateTimeField(
                blank=True,
                help_text='Fim conhecido da janela em que a ONU desconectou (primeira observação offline).',
                null=True,
                verbose_name='Janela de Desconexão (Fim)',
            ),
        ),
        migrations.AddField(
            model_name='onulog',
            name='disconnect_window_start',
            field=models.DateTimeField(
                blank=True,
                help_text='Início conhecido da janela em que a ONU desconectou (última observação online).',
                null=True,
                verbose_name='Janela de Desconexão (Início)',
            ),
        ),
    ]
