# Generated by Django 4.2.27 on 2026-02-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topology', '0014_update_fiberhome_oid_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discovery', 'Discovery'), ('polling', 'Polling'), ('power', 'Power')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progresso (%)')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Detalhe')),
                ('output', models.TextField(blank=True, default='', verbose_name='Saída')),
                ('error', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='topology.olt', verbose_name='OLT')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Job de Manutenção',
                'verbose_name_plural': 'Jobs de Manutenção',
                'indexes': [models.Index(fields=['status', 'created_at'], name='topology_ma_status_7b06d0_idx'), models.Index(fields=['kind', 'status', 'created_at'], name='topology_ma_kind_56ed74_idx'), models.Index(fields=['olt', 'status', 'created_at'], name='topology_ma_olt_id_9f9310_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancejob',
            constraint=models.CheckConstraint(check=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='topology_maintenance_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='maintenancejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('olt',), name='topology_unique_active_job_per_olt'),
        ),
    ]
