# Generated by Django 4.2.27 on 2026-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0015_maintenancejob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='cached_counts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cache de Contadores Atualizado em'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cached_offline_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Não Online (Cache)'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cached_online_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Online (Cache)'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cached_onu_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Ativas (Cache)'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cached_pon_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PONs Ativas (Cache)'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cached_slot_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Slots Ativos (Cache)'),
        ),
        migrations.AddField(
            model_name='oltpon',
            name='cached_offline_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Não Online (Cache)'),
        ),
        migrations.AddField(
            model_name='oltpon',
            name='cached_online_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Online (Cache)'),
        ),
        migrations.AddField(
            model_name='oltpon',
            name='cached_onu_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Ativas (Cache)'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='cached_offline_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Não Online (Cache)'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='cached_online_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Online (Cache)'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='cached_onu_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ONUs Ativas (Cache)'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='cached_pon_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PONs Ativas (Cache)'),
        ),
    ]
