# Generated by Codex on 2026-02-23

from django.db import migrations
from django.db.models import Count, Q
from django.utils import timezone


def _backfill_cached_counts(apps, schema_editor):
    OLT = apps.get_model("topology", "OLT")
    OLTSlot = apps.get_model("topology", "OLTSlot")
    OLTPON = apps.get_model("topology", "OLTPON")
    ONU = apps.get_model("topology", "ONU")

    now = timezone.now()
    olt_ids = list(OLT.objects.values_list("id", flat=True))

    for olt_id in olt_ids:
        active_slots = list(
            OLTSlot.objects.filter(olt_id=olt_id, is_active=True).values("id")
        )
        active_pons = list(
            OLTPON.objects.filter(olt_id=olt_id, is_active=True).values("id", "slot_id")
        )

        slot_ids = [int(row["id"]) for row in active_slots]
        pon_ids = [int(row["id"]) for row in active_pons]

        pon_count_by_slot = {}
        for row in active_pons:
            slot_id = int(row["slot_id"])
            pon_count_by_slot[slot_id] = int(pon_count_by_slot.get(slot_id, 0)) + 1

        slot_onu_stats = {}
        if slot_ids:
            slot_rows = ONU.objects.filter(
                olt_id=olt_id,
                is_active=True,
                slot_ref_id__in=slot_ids,
            ).values("slot_ref_id").annotate(
                total=Count("id"),
                online=Count("id", filter=Q(status="online")),
            )
            for row in slot_rows:
                total = int(row.get("total") or 0)
                online = int(row.get("online") or 0)
                slot_onu_stats[int(row["slot_ref_id"])] = {
                    "total": total,
                    "online": online,
                    "offline": max(total - online, 0),
                }

        slot_updates = []
        for slot_id in slot_ids:
            stats = slot_onu_stats.get(slot_id, {"total": 0, "online": 0, "offline": 0})
            slot_updates.append(
                OLTSlot(
                    id=slot_id,
                    cached_pon_count=int(pon_count_by_slot.get(slot_id, 0)),
                    cached_onu_count=int(stats["total"]),
                    cached_online_count=int(stats["online"]),
                    cached_offline_count=int(stats["offline"]),
                )
            )
        if slot_updates:
            OLTSlot.objects.bulk_update(
                slot_updates,
                [
                    "cached_pon_count",
                    "cached_onu_count",
                    "cached_online_count",
                    "cached_offline_count",
                ],
                batch_size=500,
            )

        pon_onu_stats = {}
        if pon_ids:
            pon_rows = ONU.objects.filter(
                olt_id=olt_id,
                is_active=True,
                pon_ref_id__in=pon_ids,
            ).values("pon_ref_id").annotate(
                total=Count("id"),
                online=Count("id", filter=Q(status="online")),
            )
            for row in pon_rows:
                total = int(row.get("total") or 0)
                online = int(row.get("online") or 0)
                pon_onu_stats[int(row["pon_ref_id"])] = {
                    "total": total,
                    "online": online,
                    "offline": max(total - online, 0),
                }

        pon_updates = []
        for pon_id in pon_ids:
            stats = pon_onu_stats.get(pon_id, {"total": 0, "online": 0, "offline": 0})
            pon_updates.append(
                OLTPON(
                    id=pon_id,
                    cached_onu_count=int(stats["total"]),
                    cached_online_count=int(stats["online"]),
                    cached_offline_count=int(stats["offline"]),
                )
            )
        if pon_updates:
            OLTPON.objects.bulk_update(
                pon_updates,
                ["cached_onu_count", "cached_online_count", "cached_offline_count"],
                batch_size=500,
            )

        totals = ONU.objects.filter(olt_id=olt_id, is_active=True).aggregate(
            total=Count("id"),
            online=Count("id", filter=Q(status="online")),
        )
        onu_count = int(totals.get("total") or 0)
        online_count = int(totals.get("online") or 0)
        OLT.objects.filter(id=olt_id).update(
            cached_slot_count=int(len(slot_ids)),
            cached_pon_count=int(len(pon_ids)),
            cached_onu_count=onu_count,
            cached_online_count=online_count,
            cached_offline_count=max(onu_count - online_count, 0),
            cached_counts_at=now,
        )


def _clear_cached_counts(apps, schema_editor):
    OLT = apps.get_model("topology", "OLT")
    OLTSlot = apps.get_model("topology", "OLTSlot")
    OLTPON = apps.get_model("topology", "OLTPON")

    OLT.objects.update(
        cached_slot_count=None,
        cached_pon_count=None,
        cached_onu_count=None,
        cached_online_count=None,
        cached_offline_count=None,
        cached_counts_at=None,
    )
    OLTSlot.objects.update(
        cached_pon_count=None,
        cached_onu_count=None,
        cached_online_count=None,
        cached_offline_count=None,
    )
    OLTPON.objects.update(
        cached_onu_count=None,
        cached_online_count=None,
        cached_offline_count=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("topology", "0016_olt_cached_counts_at_olt_cached_offline_count_and_more"),
    ]

    operations = [
        migrations.RunPython(_backfill_cached_counts, _clear_cached_counts),
    ]
