# Generated by Codex on 2026-02-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topology', '0017_backfill_topology_cached_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONUPowerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(verbose_name='Slot ID')),
                ('pon_id', models.IntegerField(verbose_name='PON ID')),
                ('onu_number', models.IntegerField(verbose_name='ONU ID')),
                ('onu_rx_power', models.FloatField(blank=True, null=True, verbose_name='ONU RX (dBm)')),
                ('olt_rx_power', models.FloatField(blank=True, null=True, verbose_name='OLT RX (dBm)')),
                ('read_at', models.DateTimeField(verbose_name='Leitura em')),
                (
                    'source',
                    models.CharField(
                        choices=[('scheduler', 'Scheduler'), ('manual', 'Manual'), ('scoped', 'Scoped')],
                        default='scheduler',
                        max_length=20,
                        verbose_name='Origem',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                (
                    'olt',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='power_samples',
                        to='topology.olt',
                        verbose_name='OLT',
                    ),
                ),
                (
                    'onu',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='power_samples',
                        to='topology.onu',
                        verbose_name='ONU',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Amostra de Potência da ONU',
                'verbose_name_plural': 'Amostras de Potência da ONU',
            },
        ),
        migrations.AddIndex(
            model_name='onupowersample',
            index=models.Index(fields=['olt', 'read_at'], name='topology_on_olt_id_3344e0_idx'),
        ),
        migrations.AddIndex(
            model_name='onupowersample',
            index=models.Index(fields=['onu', 'read_at'], name='topology_on_onu_id_8cb700_idx'),
        ),
        migrations.AddIndex(
            model_name='onupowersample',
            index=models.Index(fields=['olt', 'slot_id', 'pon_id', 'read_at'], name='topology_on_olt_id_1f2e57_idx'),
        ),
        migrations.AddConstraint(
            model_name='onupowersample',
            constraint=models.UniqueConstraint(fields=('onu', 'read_at'), name='topology_unique_onu_power_sample'),
        ),
        migrations.AddConstraint(
            model_name='onupowersample',
            constraint=models.CheckConstraint(
                check=models.Q(onu_rx_power__isnull=False) | models.Q(olt_rx_power__isnull=False),
                name='topology_power_sample_has_value',
            ),
        ),
    ]
