# Generated by Django 4.2.28 on 2026-03-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0022_add_history_days_to_olt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onupowersample',
            new_name='topology_on_olt_id_53cb05_idx',
            old_name='topology_on_olt_id_3344e0_idx',
        ),
        migrations.RenameIndex(
            model_name='onupowersample',
            new_name='topology_on_onu_id_cfd59a_idx',
            old_name='topology_on_onu_id_8cb700_idx',
        ),
        migrations.RenameIndex(
            model_name='onupowersample',
            new_name='topology_on_olt_id_e4beb7_idx',
            old_name='topology_on_olt_id_1f2e57_idx',
        ),
    ]
