# Generated by Django 4.2.29 on 2026-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0032_rename_snmp_health_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='collector_failure_count',
            field=models.IntegerField(default=0, verbose_name='Falhas Consecutivas do Coletor'),
        ),
        migrations.AlterField(
            model_name='olt',
            name='collector_reachable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Coletor Acessível'),
        ),
        migrations.AlterField(
            model_name='olt',
            name='last_collector_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação do Coletor'),
        ),
        migrations.AlterField(
            model_name='olt',
            name='last_collector_error',
            field=models.TextField(blank=True, default='', verbose_name='Último Erro do Coletor'),
        ),
    ]
